### ISSUE TITLE
Password not being validated

### ISSUE THREAD

**Issue by crmepham** [Tukks/cogito#31]
https://github.com/Tukks/cogito/blob/50660ed447f62f826e6713a317c36e2f243f6fb4/cogito-back/src/main/java/com/tukks/cogito/configuration/CustomAuthenticationManager.java#L28

If I am not mistaken, it doesn't appear that the password is being validated?

**Comment by Tukks** [comment]
Fixed!

I'm rebuilding all the docker image now.

**Comment by crmepham** [comment]
No problem. Are you accepting pull requests?

**Comment by Tukks** [comment]
Yes, no problem for pull request.
I will review it.
