### ISSUE TITLE
Bookmarklet possible?

### ISSUE THREAD

**Issue by booYah187** [Tukks/cogito#38]
Big fan of Cogito, finding it to be the tool I didnt know I was missing. I was wondering if there was a way to implement a bookmarklet, so i can quickly add links to Cogito from any source page on desktop. 

Also, I made an icon for my dash, if you have any use for it you are welcome to it. Can also do a pr for it if that matters.
 
![cogito](https://user-images.githubusercontent.com/95330381/235339726-3330db62-e334-4283-9aa2-ecaaa364edaa.png)

-Matt

**Comment by Tukks** [comment]
I think a bookmarklet will be easy to implement, I will try something next week. 

Thanks a lot for the logo, can I use it for the project? 
Mine is black and white, I prefer yours. 😃

**Comment by booYah187** [comment]
Sounds good, you can certainly use it for the project.

**Comment by Tukks** [comment]
@booYah187 here's the bookmarklet : 
`javascript:(function(){window.open('https://<COGITO-URL>/handle-share?text='+encodeURIComponent(window.location.href));})()`

Change Cogito-url by your url, when you click on the bookmarklet it open a new tab saving the link, like on mobile.

**Comment by booYah187** [comment]
Perfect, much obliged!
